name: Build and Commit DBT Docs
 
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.9"
 
      # Installer dbt
      - name: Install dbt
        run: |
          pip install dbt-core dbt-duckdb
 
      # Créer le fichier profiles.yml pour DBT
      - name: Create DBT profile
        run: |
          mkdir -p ~/.dbt
          echo "dbt_demo_project:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: duckdb" >> ~/.dbt/profiles.yml
          echo "      path: data/my_duckdb_file.duckdb" >> ~/.dbt/profiles.yml
      # Génére la documentation
      - name: Prepare Data Folder
        run: mkdir -p data
        
      # Génére la documentation
      - name: Generate dbt docs
        run: |
          dbt deps
          dbt compile
          dbt docs generate
 
      # Copier la doc vers /docs
      - name: Copy docs to /docs
        run: |
          mkdir -p docs
          cp -r target/* docs/
 
      # Commit + Push le dossier /docs
      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update dbt docs [automated]" || echo "No changes to commit"
          git push origin main
